import Head from "next/head";
import styled from "styled-components";
import Card from "../components/Card";
import { nanoid } from "nanoid";

export default function Home() {
  const nestingBoxes = [
    {
      id: nanoid(),
      date: "31.08.2021",
      time: "15:56 Uhr",
      latitude: 49.138844,
      longitude: 8.278068,
      nistkasten: 246,
      count: 4,
    },
  ];

  return (
    <div>
      <Head>
        <title>batSCAN</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {nestingBoxes.map((nestingbox) => (
          <Card
            key={nestingbox.id}
            id={nestingbox.id}
            date={nestingbox.date}
            time={nestingbox.time}
            latitude={nestingbox.latitude}
            longitude={nestingbox.longitude}
            nistkasten={nestingbox.nistkasten}
            count={nestingbox.count}
          />
        ))}
      </main>
    </div>
  );
}
